### ISSUE TITLE
Differences with fs?

### ISSUE THREAD

**Issue by briatte** [mkearney/fml#1]
I am struggling to understand how this package differs from `fs`:

https://fs.r-lib.org/

Perhaps it could appear in the README?

**Comment by mkearney** [comment]
This is why I haven't advertised or promoted this package at all. B/c compared to {fs}, there's not really an upside to {fml}–at least not yet. Maybe if I develop the `find_` and `search_` functions more. But I suppose I can include a note in the README.

**Comment by briatte** [comment]
Thanks for your reply :-)
